SocialHub/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from groups.views import ListGroups

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ListGroups.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks')
]

groups/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'groups'

urlpatterns = [
                  path('', views.ListGroups.as_view(), name='all'),
                  path('new/', views.CreateGroup.as_view(), name='create'),
                  path('posts/in/<slug>/', views.SingleGroup.as_view(), name='single'),
                  re_path(r'^join/(?P<slug>[-\w]+)/$', views.JoinGroup.as_view(), name='join'),
                  re_path(r'^leave/(?P<slug>[-\w]+)/$', views.LeaveGroup.as_view(), name='leave'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
                  path('', views.PostList.as_view(), name='all'),
                  path('new/', views.CreatePost.as_view(), name='create'),
                  re_path(r'^by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
                  re_path(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
                  re_path(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django import template
from django.contrib.auth import get_user_model
import misaka

User = get_user_model()

register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def Meta(self):
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from .models import Group, GroupMember
from django.shortcuts import get_object_or_404


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group


class SingleGroup(generic.DetailView):
    model = Group


class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except:
            messages.warning(self.request, 'Warning already a member!')
        else:
            messages.success(self.request, 'You are now a member')

        return super().get(self.request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug'),
            ).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group!')
        return super().get(self.request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <div class="row">

            {% block pregroup %}
            {% endblock %}

            {% block groupcontent %}
            {% endblock %}

            {% block postgroup %}
            {% endblock %}

        </div>
    </div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    <ul>
        <li>
            <h1>{{ group.name }}</h1>
        </li>
        <li>
            <h5>Member Count: {{ group.members.count }}</h5>
        </li>
        <li>
            <div class="content">
                {% if  user in group.members.all %}
                    <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-warning">Leave Group</a>
                {% else %}
                    <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-primary">Join Group</a>
                {% endif %}
            </div>
        </li>
    </ul>
{% endblock %}

{% block groupcontent %}


    {% if group.posts.count == 0 %}
        <h2>No posts in this group yet</h2>
    {% else %}
        <div class="row">
            {% for post in group.posts.all %}
                <div class="col-12">
                    {% include 'posts/_post.html' %}
                </div>
            {% endfor %}
        </div>
    {% endif %}


{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}
{% block groupcontent %}
    <h4>Create new group!</h4>

    <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="create" class="btn btn-primary">
    </form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}

    <div class="col-lg-4 col-md-12">
        {% if user.is_authenticated %}
            <h5>Welcome Back
                <a href="{% url 'posts:for_user' username=user.username %}">
                    @{{ user.username }}
                </a>
            </h5>
        {% endif %}
    </div>

    <div class="col-lg-4 col-md-12">
        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class="btn btn-primary">Create Group</a>
        {% endif %}
    </div>


{% endblock %}

{% block groupcontent %}
    {% for group in object_list %}
        <div class="row">
            <div class="card ">
                <div class="card-body">
                    <a href="{% url 'groups:single' slug=group.slug %}">
                        <h3 class="title list-group-item-heading">{{ group.name }}</h3>
                    </a>
                    {{ group.description }}
                    <span class="badge">{{ group.members.count }}</span>
                    member{{ group.members.count|pluralize }}
                    <span class="badge">{{ group.posts.count }}</span>
                    post{{ group.posts.count|pluralize }}
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}